package com.example.duanwu.tao_taos.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.duanwu.tao_taos.BeanDao;

import com.example.duanwu.tao_taos.dao.BeanDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig beanDaoDaoConfig;

    private final BeanDaoDao beanDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        beanDaoDaoConfig = daoConfigMap.get(BeanDaoDao.class).clone();
        beanDaoDaoConfig.initIdentityScope(type);

        beanDaoDao = new BeanDaoDao(beanDaoDaoConfig, this);

        registerDao(BeanDao.class, beanDaoDao);
    }
    
    public void clear() {
        beanDaoDaoConfig.clearIdentityScope();
    }

    public BeanDaoDao getBeanDaoDao() {
        return beanDaoDao;
    }

}
